function [peaks, locs, widths, prominences, peakMin] = analyzeTraceOS(timeBase,...
    trace, peakHeightThresholds, peakDistance, minPeakProminence,...
    minMinProminence, minMinWidth, outputDirectory, scanName,maxPeakWidth,...
    minPeakWidth) 
%ANALYZETRACEOS Analyzes traces generated by getOSContractilyTrace
%   [peaks, locs, widths, prominences, excelOutputPath, outputTitle,
%   outputVariable] = analyzeTraceOS(timeBase, trace, peakHeightThresholds,
%   peakDistance,minMinProminence, minMinWidth, outputDirectory, scanName,
%   ) will analyze the contractility trace. It will find
%   the peaks higher than peakHightThreshold separated by more than
%   peakDistance, of minimum prominence minPeakProminence. It will also
%   find the minimum before the each peack, peakMin, using the minimum
%   prominence minMinProminence and minimun width minMinWidth. It prints
%   the traces annotated marked with the peaks and minima to the
%   outputDirectory. It returns the peaks, locs, widths, prominences and
%   peakMin discovered.

outputName = extractBefore(scanName,'.');

figure;

% Find all peaks 
[peaks, locs, widths, prominences] = findpeaks(trace, 'MinPeakHeight', ...
    peakHeightThresholds, 'MinPeakDistance', peakDistance, ...
    'MinPeakProminence', minPeakProminence, 'WidthReference', 'halfprom', ...
    'MaxPeakWidth', maxPeakWidth, 'MinPeakWidth', minPeakWidth);

% Find all minima

invertedTrace= max(trace(:))-trace;
[mins, locsMin] = findpeaks(invertedTrace,'MinPeakProminence', ...
    minMinProminence,'MinPeakWidth',minMinWidth);

%Keep only the minimums before a peak
peakMin = zeros(size(peaks));

for i = 1:size(locs,1)
   peakMinInd = find(locsMin < locs(i), 1 , 'last');
   if peakMinInd ~= 0
   peakMin(i) = locsMin(peakMinInd);
    else peakMin(i) = 1;
    end
end

% Plot and save
figure;
% plot(timeBase, trace, 'x-');
set(gcf, 'Position', [92 375 1472 423]);
currentAxis = axis;
hold on;

plot(trace, '-x'),hold on, plot(locs, trace(locs),'rx', 'MarkerSize', 15);
plot(peakMin, trace(peakMin),'ro', 'MarkerSize', 10);

xlabel('Time (seconds)', 'FontSize', 10);
ylabel('Magnitude', 'FontSize', 10);

graphTitle =  strrep(outputName,'_',' ');
title(['Trace for ' graphTitle], 'FontSize', 10);
saveas(gcf, [outputDirectory outputName '_peaks' '.fig'], 'fig');
saveas(gcf, [outputDirectory outputName '_peaks' '.jpg'], 'jpeg');
figure;
        
close all;

end

